// <auto-generated />
using System;
using Beblue.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beblue.Data.Migrations
{
    [DbContext(typeof(BeblueContext))]
    [Migration("20190624230645_MappingSaleAndOrderItems")]
    partial class MappingSaleAndOrderItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Beblue.Domain.Discs.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Discs");
                });

            modelBuilder.Entity("Beblue.Domain.Sales.CashBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.Property<decimal>("Value");

                    b.Property<int>("WeekDay");

                    b.HasKey("Id");

                    b.ToTable("CashBack");
                });

            modelBuilder.Entity("Beblue.Domain.Sales.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Beblue.Domain.Sales.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CashBackId");

                    b.Property<int>("DiscId");

                    b.Property<int>("Quantity");

                    b.Property<int>("SaleId");

                    b.Property<int?>("SaleId1");

                    b.HasKey("Id");

                    b.HasIndex("CashBackId");

                    b.HasIndex("DiscId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SaleId1");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Beblue.Domain.Sales.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Beblue.Domain.Sales.OrderItem", b =>
                {
                    b.HasOne("Beblue.Domain.Sales.CashBack", "CashBack")
                        .WithMany()
                        .HasForeignKey("CashBackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Beblue.Domain.Discs.Disc", "Disc")
                        .WithMany()
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Beblue.Domain.Sales.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Beblue.Domain.Sales.Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId1");
                });

            modelBuilder.Entity("Beblue.Domain.Sales.Sale", b =>
                {
                    b.HasOne("Beblue.Domain.Sales.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
